### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by THEBEST1278** [Project-Bradnails/Bradnails#10]
Every time I click on one of the games to download it says I need access and it won't let me in. Is there a way to fix this?

**Comment by ProjectBradnails** [comment]
Hello @THEBEST1278 
Which games were you trying to download?

-Stansfield

**Comment by THEBEST1278** [comment]
i tried call of duty and some others but mostly COD

**Comment by Caesar-1dev** [comment]
ill look into it
