### ISSUE TITLE
New Super Mario Bros Wii

### ISSUE THREAD

**Issue by CassetteeTape** [Project-Bradnails/Bradnails#11]
This is a really minor issue but New Super Mario Bros Wii is repeated twice under the Dolphin Emulator section. I don't know if it was supposed to be a different game or it was just a Copy and Paste issue because they both lead to the same download page. 
![Dolphin](https://user-images.githubusercontent.com/98529955/159491341-679000aa-dbd0-4d06-932b-71686fa6b97f.PNG)

**Comment by ProjectBradnails** [comment]
Hello @CassetteeTape 
Thanks for letting us know.
