### ISSUE TITLE
Bruuuuuuuuuuuuh

### ISSUE THREAD

**Issue by ToomySoManley** [Project-Bradnails/Bradnails#13]
Is there another way to get the games?

**Comment by Caesar-1dev** [comment]
> Is there another way to get the games?

How do you mean? @ToomySoManley

**Comment by ProjectBradnails** [comment]
> Is there another way to get the games?

What I assume you mean is any other way than google drive.

The answer is we don't have anything else setup because there are no good alternatives.

**Comment by ToomySoManley** [comment]
ok thanks
