### ISSUE TITLE
Remaking this repo

### ISSUE THREAD

**Issue by avourr** [Project-Bradnails/Bradnails#19]
Hi bradnails devs. Considering this repo is not in use anymore. May i make a another unblocked games archive similar to this and use some of the google drive links to put in my own repo? Ill credit on all of the links if you want.

**Comment by Caesar-1dev** [comment]
Hey, your more than welcome to do so. I might start updating and adding things solo, but as long as you credit us I have no problems

**Comment by avourr** [comment]
alright thanks <3

**Comment by avourr** [comment]
would i be able to help this project like add games and such
