### ISSUE TITLE
Portal 2 seems to be missing a file

### ISSUE THREAD

**Issue by C4-621Raven** [Project-Bradnails/Bradnails#28]
Portal 2 is giving the following error when attempting to run the LAUNCHER application.

![Screenshot 2023-02-07 075130 (2)](https://user-images.githubusercontent.com/115633057/217250655-ff680b0e-ea13-459a-bea5-63df3e5fc690.png)

I have attempted to just run the portal2 application but that closed as soon as it got to the start screen.
I also tried downloading the file three times to ensure that there wasn't an error with the download but it still gives the same error.

**Comment by C4-621Raven** [comment]
Turns out that there was a file missing from my computer (it's my school computer, so I assume this was intentional). After gaining admin access to the computer, I installed the missing file myself.

**Comment by cfishe02** [comment]
do you or did you have Geometry dash because geo dash works and has the same files as portal 2 with the msvcp100.dll and msvcr100.dll
