### ISSUE TITLE
The video for how to use dolphin is blocked on youtube for me

### ISSUE THREAD

**Issue by CO5MIC21** [Project-Bradnails/Bradnails#30]
![SharedScreenshot](https://user-images.githubusercontent.com/126168917/220911879-b7f5011d-1673-472b-b2fb-17f06f4bede3.jpg)

**Comment by amhooman** [comment]
Then find your own tutorial

**Comment by p0syd0n** [comment]
not tryna be toxic but that is a you problem, the devs can't fix your admin's google account rules

**Comment by CO5MIC21** [comment]
yeah i get it, i realised how stupid i sounded when i posted it, anyways
thanks for what your doing school is actually fun now
