### ISSUE TITLE
Geometry Dash is blocked 

### ISSUE THREAD

**Issue by Runsfornoreason21** [Project-Bradnails/Bradnails#40]
Hey devs so every time i try to download geometry dash it says it violates googles terms of service and why have you not f**king fixed it yet?  
And i got this 
![289897274-29b98845-4038-43af-96d7-035e4ef96e36](https://github.com/Project-Bradnails/Bradnails/assets/119550115/149ae089-3b35-46c7-87a1-cedf00c38574)

**Comment by ProjectBradnails** [comment]
Firstly, no need to get rude, that isn't going to help your cause, and secondly, this project is currently not being maintained as we are focusing on other aspects of our lives, it is possible we may come back but at the moment, no further updates will be made. If someone wants to upload the game and push a merge request, we will vet it and push it to the repository, however, we aren't going to take the time to find which games have been removed and reupload them all.

**Comment by Runsfornoreason21** [comment]
I apologize for my behavior i was a little ticked off by it and i did not mean to be rude and it's just hard keeping up to date with everything and i respect that
