### ISSUE TITLE
I HAVE AVENGERS ENDGAME

### ISSUE THREAD

**Issue by BeeBoonana** [Project-Bradnails/Bradnails#42]
werent you doing to add avengers endgame? ill give it to you if you want it also i have moana and x men 2 also 1080p spider man across the spiderverse

**Comment by VWMM** [comment]
@BeeBoonana can u drop endgame pls?

**Comment by BeeBoonana** [comment]
@VWMM i gotta wait like 2 days for the smash link and it wont let me copy it to github its just the cd i have a shortcut to take you directly to the options thing so i will be back

**Comment by BeeBoonana** [comment]
@VWMM I FIGURED OUT HOW TO MAKE A GOOGLE DRIVE LINK https://drive.google.com/drive/u/1/folders/13UCOesGQwcWBTV9NsrUQ-bMmKmN8Mh5s

**Comment by MoltenWolf85** [comment]
WELL, OF COURSE WE WANT ENDGAME. PLEASE

**Comment by ProjectBradnails** [comment]
Please submit a push request and once we vet it, we will push to onto the site, however we don't actively manage it anymore, so if you guys want something you guys have to find it and make a request to get it on the site.

**Comment by MoltenWolf85** [comment]
I am currently uploading Endgame to my Drive right now. How would I submit it? Just as a Google drive link?

**Comment by MoltenWolf85** [comment]
Never mind

**Comment by ProjectBradnails** [comment]
Yep, as a google drive link.
