### ISSUE TITLE
Project Zomboid Link

### ISSUE THREAD

**Issue by Commander0Silverthorn** [Project-Bradnails/Bradnails#43]
Hello Slash,

I would like to let you know that the project Zomboid link is not working, I would like it very much if you could fix the link for us, in addition, there are some games that I could give you to add to "Project Bradnails"

Thank you for your time,
Commander0Silverthorn

**Comment by ProjectBradnails** [comment]
Hi, we don't actively maintain the site anymore so when a game is deleted, it is up to the community to find a new one, create a google drive link, and then submit the file in a push/merge request. We will vet the file and approve it. If you have a new game, you can submit it in the same forum as the patch.
