### ISSUE TITLE
The Binding of isaac: Repentance

### ISSUE THREAD

**Issue by jujuondabe** [Project-Bradnails/Bradnails#47]
Do you guys think you will be able to add TBOI repentance sooner or later now that Repentance+ is out?  afterbirth+ is aiight but repentance adds so much more, i don't know how to get it myself so you guys adding it would be dope, 
if not its fine, but thanks anyway

**Comment by ProjectBradnails** [comment]
Please refer to the statement on the main page of the repository-

Hi Guys, We are no longer actively managing and checking up on the status of the files on the repository. That means that if a file gets taken down by google, it may not be reuploaded. However, if someone in the community finds a new file, and submits a patch/push request to the code, we will take a look at the file (to make sure it isn't malicious, and then push it to the site. In a way, this project is now in the hands of the community, you guys will determine whether it stays alive, but with the activity we still see even 3 years after the project initially concluded, I am sure that Bradnails will remain a free and accessible souce for all your games and movies.

-Stanfield

**Comment by jujuondabe** [comment]
how would i get the game files from steam?, so i can do the push request
