### ISSUE TITLE
chrome

### ISSUE THREAD

**Issue by gamecreator33** [Project-Bradnails/Bradnails#5]
Hello! I use a chromebook so is there any way that you can make some of these games compatible on Chromebook?

**Comment by ProjectBradnails** [comment]
Hello, although we would like to be able to support chromebooks, the devs only have windows laptops, and wouldn't be able to test for compatibility. Additionally, none of these games are optimized for chrome and would have issues running. I would say your best bet is to try movies instead. Sorry for the inconvenience.

**Comment by Caesar-1dev** [comment]
also chrome doesn't support .exes and that is the main problem with chrome os

**Comment by FNFFAN737** [comment]
Although you can still watch movies and shows!
