### ISSUE TITLE
Pls share with me

### ISSUE THREAD

**Issue by om3ga6400** [Project-Bradnails/Bradnails#6]
im 4053800@ccpsnet.net i asked for access

**Comment by Caesar-1dev** [comment]
@OMEGA640 what did you want shared with you/ wanted access to?

**Comment by ProjectBradnails** [comment]
Hi OMEGA, can I inquire on what you are requesting access to? Thanks.

**Comment by om3ga6400** [comment]
everything on the "games list"

**Comment by Caesar-1dev** [comment]
everything is accessible with the links provided
