### ISSUE TITLE
Expansion

### ISSUE THREAD

**Issue by 420Boss** [Project-Bradnails/Bradnails#7]
Ok so i love this its helped me get through boring classes more than once,but 2 things:
1. can we get guardians of the galaxy 1?
2. is there a way to put games on the Chromebook instead of windows?

thank you anyway!

**Comment by Caesar-1dev** [comment]
> Ok so i love this its helped me get through boring classes more than once,but 2 things:
> 
> 1. can we get guardians of the galaxy 1?
> 2. is there a way to put games on the Chromebook instead of windows?
> 
> thank you anyway!

So because the games we uploaded are .exes, they are sadly not chrome os compatible but i will look into GotG one and two

**Comment by 420Boss** [comment]
THANK YOU
