### ISSUE TITLE
issue with downloading

### ISSUE THREAD

**Issue by GabrielisCoder** [Project-Bradnails/Bradnails#9]
so with the downloading there are one or two games that dont work but the main thing is that all of the games like mario and stuff are all.biz or somthing and it does not download

**Comment by ProjectBradnails** [comment]
Hello @GabrielisCoder 

Could you specify which games exactly aren't working. 

Some games do slip passed our process of checking, we apologize for the inconvenience.

**Comment by GabrielisCoder** [comment]
so pretty much teh games that arent working are the ones that are below to game tab. everything under the retroarch tab and every thing below that they are all .Biz or just something random that wont download. also i am doing this ona school laptop because all gaming site are blocked so it was cool and fun to download but now when i click on the game it says "this has been blocked by administrator" so i am assuming that is because it is a .exe file or maybe they just blokced the games in general so i willtry to redownload them and tell you if it works or not. ps. if you know any gaming sites like yours or unblocked site those would be good to know. anyway i hope you have a good day.

**Comment by ProjectBradnails** [comment]
I don't believe anyone else is having that issue. If you could specify the type of laptop you have, i need to know this to confirm if I will be able to to you.

Stansfield

**Comment by GabrielisCoder** [comment]
my laptop is a 2018 dell

**Comment by u4pak** [comment]
1: For the ".biz" files or whatever, I believe you are downloading the ROM files needed to be used on RetroArch. These are mainly singular files that you load into the emulator, and are not standalone programs. 

2: For the blocking situation, what exactly is being blocked? The download links or the executable itself?

**Comment by ProjectBradnails** [comment]
This thread has been either resolved or ceased.
